---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: koti-deployment
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: koti-koti
  template:
    metadata:
      labels:
        app: koti-koti
    spec:
      containers:
      - name: koti-koti-container
        image: koteswarararaosairi/kk:v6  # Update this to your Docker image if needed
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "200m"
            memory: "512Mi"
          limits:
            cpu: "500m"
            memory: "1Gi"
---
apiVersion: v1
kind: Service
metadata:
  name: koti-service
  namespace: default
spec:
  type: LoadBalancer  # LoadBalancer for external access
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: koti-koti
