---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: koti-deployment
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: koti-koti
  template:
    metadata:
      labels:
        app: koti-koti
    spec:
      containers:
      - name: koti-koti-container
        image: ramki1027/image1  # Use your Docker image name here
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "200m"
            memory: "512Mi"
          limits:
            cpu: "500m"
            memory: "1Gi"

---
apiVersion: v1
kind: Service
metadata:
  name: koti-service
  namespace: default
spec:
  type: LoadBalancer  # This will expose your app externally in a cloud provider
  ports:
  - port: 80
    targetPort: 8080  # Match the port your container listens on
  selector:
    app: koti-koti
